project:
  type: book
  output-dir: _book

book:
  title: "Mastering Nextflow: From Fundamentals to Expert Practice"
  author: "Shaojun Xie"
  chapters:
  - index.qmd
  - preface.qmd
  - introduction.qmd

  - part: Foundations
    chapters: 
      - workflow_overview.qmd
      - channels_processes.qmd
      - DSL2.qmd

  - part: Building Real Pipelines
    chapters:
      - 03-results.qmd
  
  - part: Advanced Topics
    chapters:
      - 04-advanced_metadata.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  # pdf:
  #   toc: true
  #   number-sections: true
    #include-in-header: preamble.tex
    

publish:
  on: gh-pages
