project:
  type: book
  output-dir: _book

book:
  title: "DNA Methylation Analysis with Nextflow"
  author: "Shaojun Xie"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-methods.qmd
    - 03-results.qmd
    - 03-advanced_metadata.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true

publish:
  on: gh-pages
